name: Run tests on any Push event

on:
  push:
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install -r testrequirements.txt

      - name: Run tests
        run: coverage run --omit 'venv/*' -m unittest
      - name: Tests report
        run: coverage report